name       : qt5-webview
version    : 5.13.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.1/submodules/qtwebview-everywhere-src-5.13.1.tar.xz : bb369f8addf573d2f984a5afef26219c97dd895764eb0bbcc7296e358530de6f
license    : 
    - BSD-3-Clause
    - GFDL-1.3-only
    - GPL-2.0-or-later
component  : desktop.qt
summary    : Provides a way to display web content in a QML application
description: |
    Provides a way to display web content in a QML application
builddeps  :
    - pkgconfig(Qt5WebEngine)
setup      : |
    %qmake CONFIG+=release qtwebview.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
