name       : qt5-webview
version    : 5.13.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.2/submodules/qtwebview-everywhere-src-5.13.2.tar.xz : 394cc7a9cb29b7883816ff3137b022f30568151aada0739fc99a23789c21c015
homepage   : https://www.qt.io
license    :
    - BSD-3-Clause
    - GFDL-1.3-only
    - GPL-2.0-or-later
component  : desktop.qt
summary    : Provides a way to display web content in a QML application
description: |
    Provides a way to display web content in a QML application
builddeps  :
    - pkgconfig(Qt5WebEngine)
setup      : |
    %qmake CONFIG+=release qtwebview.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
