name       : qt5-webview
version    : 5.15.2
release    : 6
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtwebview-everywhere-src-5.15.2.tar.xz : be9f46167e4977ead5ef5ecf883fdb812a4120f2436383583792f65557e481e7
homepage   : https://www.qt.io
license    :
    - BSD-3-Clause
    - GFDL-1.3-only
    - GPL-2.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Provides a way to display web content in a QML application
description: |
    Provides a way to display web content in a QML application
builddeps  :
    - pkgconfig(Qt5WebEngine)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtwebview.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
