name       : qt5-webview
version    : 5.15.9
release    : 13
source     :
    - git|https://invent.kde.org/qt/qt/qtwebview.git : 23d67d0de3301dbed5d8c5880b6cf60bfa9eeb2a
homepage   : https://www.qt.io
license    :
    - BSD-3-Clause
    - GFDL-1.3-only
    - GPL-2.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Provides a way to display web content in a QML application
description: |
    Provides a way to display web content in a QML application
builddeps  :
    - pkgconfig(Qt5WebEngine)
patterns   :
    - demos : /usr/lib64/qt5/examples
setup      : |
    %qmake CONFIG+=release qtwebview.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
